//
// Created by Dmitriy on 9/17/26.
//

#ifndef JSUPERVISOR_MAC_NOTIFY_H
#define JSUPERVISOR_MAC_NOTIFY_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once
#include <jni.h>
/* Header for class MacNotification */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MacNotification
 * Method:    sendNotification
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_faketri_utils_NotificationSystem_notify
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif //JSUPERVISOR_LINUX_NOTIFY_H
